config/routes.rb
Rails.application.routes.draw do

  resources :admins
  root to: "home#index"
  
  resources :trains do
  end
  get 'search', to: "trains#search"

  resources :stations
  resources :transactions 
  post '/buy_ticket_form', to: 'transactions#buy_ticket_form'
  post '/buy_ticket', to: 'transactions#buy_ticket'

  resources :train_routes
  
  resources :home, only: [:index] do
    get :autocomplete_station_name, on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/station.rb
class Station < ApplicationRecord
    belongs_to :train_route
    has_many :arriving_stations, foreign_key: :arrival_station_id, class_name: 'TrainRoute'
    has_many :departing_stations, foreign_key: :departure_station_id, class_name: 'TrainRoute'
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name, :city, :address)
    end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_form.html.erb
<%= form_with(model: station, local: true) do |form| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :station_name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :station_city %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :station_address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>
<div class="row justify-content-center">

    <%= render 'form', station: @station %>

    <%= link_to 'Show', @station %> |
    <%= link_to 'Back', stations_path %>
</div>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stations</h1>
<div class="row justify-content-center">

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>City</th>
        <th>Address</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @stations.each do |station| %>
        <tr>
          <td><%= station.name %></td>
          <td><%= station.city %></td>
          <td><%= station.address %></td>
          <td><%= link_to 'Show', station %></td>
          <td><%= link_to 'Edit', edit_station_path(station) %></td>
          <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</div>
  <%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New Station</h1>
<div class="row justify-content-center">

    <%= render 'form', station: @station %>

    <%= link_to 'Back', stations_path %>
</div>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row justify-content-center">
    <p>
      <strong>Name:</strong>
      <%= @station.name %>
    </p>

    <p>
      <strong>City:</strong>
      <%= @station.city %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @station.address %>
    </p>
</div>

    <%= link_to 'Edit', edit_station_path(@station) %> |
    <%= link_to 'Back', stations_path %>