config/routes.rb
Rails.application.routes.draw do

  resources :admins
  root to: "home#index"
  
  resources :trains do
  end
  get 'search', to: "trains#search"

  resources :stations
  resources :transactions 
  post '/buy_ticket_form', to: 'transactions#buy_ticket_form'
  post '/buy_ticket', to: 'transactions#buy_ticket'

  resources :train_routes
  
  resources :home, only: [:index] do
    get :autocomplete_station_name, on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord
    has_one :train_route
    
    def has_places
        true if passengers_capacity > 0
        false
    end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  
  skip_before_action :http_basic_authenticate, :only => [:search]
  
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.includes(:train_route).all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to @train, notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    departure_station = Station.find_by(name: params[:departure_station])
    arrival_station = Station.find_by(name: params[:arrival_station])
    @trains = Train.joins(:train_route).where('train_routes.departure_station_id = ? and train_routes.arrival_station_id = ? and passengers_capacity > 0', departure_station.id, arrival_station.id)
    respond_to do |format|
      format.html 
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:departure_station_id, :arrival_station_id, :departure_time, :arrival_time, :passengers_capacity, :price)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/_form.html.erb
<%= form_with(model: train, local: true) do |form| %>
  <% if train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% train.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :train_route %>
    <%= form.number_field :train_route, id: :train_route %>
  </div>

  <div class="field">
    <%= form.label :passengers_capacity %>
    <%= form.number_field :passengers_capacity, id: :train_passengers_capacity %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :train_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trains/edit.html.erb
<h1>Editing Train</h1>
<div class="row justify-content-center">

    <%= render 'form', train: @train %>

    <%= link_to 'Show', @train %> |
    <%= link_to 'Back', trains_path %>
</div>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>
<div class="row justify-content-center">

  <table>
    <thead>
      <tr>
        <th>Departure station</th>
        <th>Arrival station</th>
        <th>Passengers capacity</th>
        <th>Price</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @trains.each do |train| %>
        <tr>
          <td><%= train.train_route.departure_station.name %></td>
          <td><%= train.train_route.arrival_station.name %></td>
          <td><%= train.passengers_capacity %></td>
          <td><%= train.price %></td>
          <td><%= link_to 'Show', train %></td>
          <td><%= link_to 'Edit', edit_train_path(train) %></td>
          <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Train', new_train_path %>
</div>

app/views/trains/new.html.erb
<h1>New Train</h1>
<div class="row justify-content-center">

    <%= render 'form', train: @train %>

</div>
    <%= link_to 'Back', trains_path %>

app/views/trains/search.html.erb
 <h1>Search results</h1>
            <div class="row justify-content-center">
                <div class="col-6">
                <% if @trains.present? %>
                <% @trains.each do |train| %>
                    <table>
                        <thead>
                            <tr>
                            <th>Departure station</th>
                            <th>Arrival station</th>
                            <th>Passengers capacity</th>
                            <th>Price</th>
                            <th></th>
                            </tr>
                        </thead>
                        <tbody>
                             <tr>
                                <td><%= train.train_route.departure_station.name %></td>
                                <td><%= train.train_route.arrival_station.name %></td>
                                <td><%= train.passengers_capacity %></td>
                                <td><%= train.price %></td>
                                <td>
                                <%= form_with url: buy_ticket_form_path, local: true do |form| %>
                                     <%= hidden_field(:train, :train, :value => train.id) %>
                                     <%= hidden_field(:cost, :cost, :value => train.price) %>
                                    <%= form.submit 'Buy', class: 'btn submit'%>
                                        <% end %>

                                
                                </td>

                            </tr>
                        </tbody>
                <% end %>
                <% else %>
                <center><h3>No trains has been found, please try again later</h3></center>
                <% end %>
                </div>            
            </div>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row justify-content-center">

  <p>
    <strong>Departure station:</strong>
    <%= @train.departure_station_id %>
  </p>

  <p>
    <strong>Arrival station:</strong>
    <%= @train.arrival_station_id %>
  </p>

  <p>
    <strong>Departure time:</strong>
    <%= @train.departure_time %>
  </p>

  <p>
    <strong>Arrival time:</strong>
    <%= @train.arrival_time %>
  </p>

  <p>
    <strong>Passengers capacity:</strong>
    <%= @train.passengers_capacity %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @train.price %>
  </p>

  <%= link_to 'Edit', edit_train_path(@train) %> |
  <%= link_to 'Back', trains_path %>
</div>