config/routes.rb
Rails.application.routes.draw do

  resources :admins
  root to: "home#index"
  
  resources :trains do
  end
  get 'search', to: "trains#search"

  resources :stations
  resources :transactions 
  post '/buy_ticket_form', to: 'transactions#buy_ticket_form'
  post '/buy_ticket', to: 'transactions#buy_ticket'

  resources :train_routes
  
  resources :home, only: [:index] do
    get :autocomplete_station_name, on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train_route.rb
class TrainRoute < ApplicationRecord
    belongs_to :train
    
    has_many :stations
    belongs_to :departure_station, class_name: 'Station'
    belongs_to :arrival_station, class_name: 'Station'
end

app/controllers/train_routes_controller.rb
class TrainRoutesController < ApplicationController
  
    before_action :set_train_route, only: [:show, :edit, :update, :destroy]
  
    # GET /train_routes
    # GET /train_routes.json
    def index
      @train_routes = TrainRoute.includes(:departure_station, :arrival_station).all
      byebug
    end
  
    # GET /train_routes/1
    # GET /train_routes/1.json
    def show
    end
  
    # GET /train_routes/new
    def new
      @train_route = TrainRoute.new
      @stations = Station.all
      @trains = Train.all
    end
  
    # GET /train_routes/1/edit
    def edit
      @stations = Station.all
      @trains = Train.all
    end
  
    # POST /train_routes
    # POST /train_routes.json
    def create
      @train_route = TrainRoute.new(train_route_params)
  
      respond_to do |format|
        if @train_route.save
          format.html { redirect_to @train_route, notice: 'TrainRoute was successfully created.' }
          format.json { render :show, status: :created, location: @train_route }
        else
          format.html { render :new }
          format.json { render json: @train_route.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /train_routes/1
    # PATCH/PUT /train_routes/1.json
    def update
      respond_to do |format|
        if @train_route.update(train_route_params)
          format.html { redirect_to @train_route, notice: 'TrainRoute was successfully updated.' }
          format.json { render :show, status: :ok, location: @train_route }
        else
          format.html { render :edit }
          format.json { render json: @train_route.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /train_routes/1
    # DELETE /train_routes/1.json
    def destroy
      @train_route.destroy
      respond_to do |format|
        format.html { redirect_to train_routes_url, notice: 'TrainRoute was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    def search
      departure_station = params[:departure_station]
      arrival_station = params[:arrival_station]
      @train_routes = TrainRoute.where('departure_station: ? and arrival_station: ? and passenger_capacity > 0', departure_station, arrival_station)
      respond_to do |format|
        format.html 
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constrain_routets between actions.
      def set_train_route
        @train_route = TrainRoute.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def train_route_params
        params.require(:train_route).permit(:departure_station_id, :arrival_station_id, :train)
      end
  end
  

app/views/train_routes/_form.html.erb
<%= form_with(model: train_route, local: true) do |form| %>
  <% if train_route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(train_route.errors.count, "error") %> prohibited this train route from being saved:</h2>

      <ul>
      <% train_route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :departure_station %>
    <%= select_tag "departure_station", options_from_collection_for_select(@stations, "id", "name") %>
  </div>

  <div class="field">
    <%= form.label :arrival_station %>
    <%= select_tag "arrival_station", options_from_collection_for_select(@stations, "id", "name") %>
  </div>

  <div class="field">
    <%= form.label :train %>
    <%= select_tag "train", options_from_collection_for_select(@trains, "id", "id") %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/train_routes/edit.html.erb
<h1>Editing Train Route</h1>
<div class="row justify-content-center">

    <%= render 'form', train_route: @train_route %>

    <%= link_to 'Show', @train_route %> |
    <%= link_to 'Back', train_routes_path %>
</div>

app/views/train_routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Train Routes</h1>
<div class="row justify-content-center">
<table>
  <thead>
    <tr>
      <th>Departure station</th>
      <th>Arrival station</th>
      <th>Train</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @train_routes.each do |train_route| %>
      <tr>
        <td><%= train_route.departure_station.name %></td>
        <td><%= train_route.arrival_station.name %></td>
        <td><%= train_route.train.id %></td>
        <td><%= link_to 'Show', train_route %></td>
        <td><%= link_to 'Edit', edit_train_route_path(train_route) %></td>
        <td><%= link_to 'Destroy', train_route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>
<%= link_to 'New Train', new_train_route_path %>

app/views/train_routes/new.html.erb
<h1>New Train Route</h1>
<div class="row justify-content-center">

    <%= render 'form', train: @train_route %>

    <%= link_to 'Back', train_routes_path %>
</div>

app/views/train_routes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row justify-content-center">

      <p>
        <strong>Departure station:</strong>
        <%= @train.departure_station_id %>
      </p>

      <p>
        <strong>Arrival station:</strong>
        <%= @train.arrival_station_id %>
      </p>

      <p>
        <strong>Train:</strong>
        <%= @train.passengers_capacity %>
      </p>

</div>

      <%= link_to 'Edit', edit_train_route_path(@train_route) %> |
      <%= link_to 'Back', train_routes_path %>